name: Update smdev db
on: 
  workflow_dispatch:
 
jobs:
  tweet:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version needed
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute update-smdev.py script # run update-smdev-db.py
        run: python update-smdev.py

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update data