name: Send a Tweet for each new game
on: 
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'
      
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # install the python version needed
      
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
            STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
            TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
            TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
            TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
            TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
            TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
            PAT_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
            PAT_GITHUB_USERNAME: ${{ secrets.PAT_GITHUB_USERNAME }}
        run: python main.py >> log_file.log

