name: Send a Tweet
on: 
    workflow_dispatch:
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "Hi, this is a test!"
          TWITTER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
